trigger:
  branches:
    include:
      - main  # Trigger pipeline on changes to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  sqlServerName: 'jsdbserver.mysql.database.azure.com'  # Replace with your actual Azure SQL Server Name
  databaseName: 'jsfirstdb'  # Replace with your database name
  adminUser: 'rootdb'  # Replace with your DB admin username
  adminPassword: 'Secret55'  # Replace with your DB admin password
  #MYSQL_HOST: ${{ secrets.DB_HOST }}
  #MYSQL_USER: ${{ secrets.DB_ADMIN_USER }}
  #MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
  #MYSQL_DB: ${{ secrets.DB_NAME_2 }}

stages:
  - stage: DeployDatabase
    displayName: Deploy Database
    jobs:
      - job: DeploySQL
        displayName: Execute SQL Scripts
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'

          # Step to install MySQL connector for Python
          - script: |
              python -m pip install --upgrade pip
              pip install mysql-connector-python
            displayName: Install MySQL Connector

          # Step to execute 'create_table.sql'
          - script: |
              echo "Deploying create_table.sql"
              python execute_sql_script.py create_table.sql
            displayName: Run create_table.sql

          # Step to execute 'update_table.sql'
          - script: |
              echo "Deploying update_table.sql"
              python execute_sql_script.py update_table.sql
            displayName: Run update_table.sql

          # Step to validate the schema update (check if column exists)
          - script: |
              echo "Validating schema update"
              python validate_schema_update.py
            displayName: Validate Schema Update
